on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Setup Nox
        run: pip install -r requirements.txt
      - name: Lint
        run: nox -s lint
      - name: Tests
        run: nox -s tests
