on:
  pull_request:
    branches:    
      - main
  push:
    branches:
      - main

jobs:
  Nox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Nox
        run: python3 -m pip install nox
      - name: Lint
        run: nox -s lint
      - name: Tests
        run: nox -s tests

